/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author GIKO
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCustomer = new javax.swing.JMenu();
        menuAddCustomer = new javax.swing.JMenuItem();
        menuSearchCustomer = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuBookTicket = new javax.swing.JMenuItem();
        menuTicketReport = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuAddFlight = new javax.swing.JMenuItem();
        menuSearchFlight = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuCreateUser = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1360, 760));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        menuCustomer.setText("Customer");

        menuAddCustomer.setText("Add Customer");
        menuAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddCustomerActionPerformed(evt);
            }
        });
        menuCustomer.add(menuAddCustomer);

        menuSearchCustomer.setText("Search Customer");
        menuSearchCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSearchCustomerActionPerformed(evt);
            }
        });
        menuCustomer.add(menuSearchCustomer);

        jMenuBar1.add(menuCustomer);

        jMenu2.setText("Tickets");

        menuBookTicket.setText("Book Ticket");
        menuBookTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBookTicketActionPerformed(evt);
            }
        });
        jMenu2.add(menuBookTicket);

        menuTicketReport.setText("Ticket Report");
        menuTicketReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTicketReportActionPerformed(evt);
            }
        });
        jMenu2.add(menuTicketReport);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Flight");

        menuAddFlight.setText("Add Flight");
        menuAddFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddFlightActionPerformed(evt);
            }
        });
        jMenu3.add(menuAddFlight);

        menuSearchFlight.setText("Search Flight");
        menuSearchFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSearchFlightActionPerformed(evt);
            }
        });
        jMenu3.add(menuSearchFlight);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("User");

        menuCreateUser.setText("Create User");
        menuCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCreateUserActionPerformed(evt);
            }
        });
        jMenu4.add(menuCreateUser);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**/
    private void menuAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddCustomerActionPerformed
        // TODO add your handling code here:
        AddCustomer cus = new AddCustomer();
        jDesktopPane1.add(cus);
        cus.setVisible(true);
    }//GEN-LAST:event_menuAddCustomerActionPerformed

    private void menuSearchCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSearchCustomerActionPerformed
        // TODO add your handling code here:
        SearchCustomer scus = new SearchCustomer();
        jDesktopPane1.add(scus);
        scus.setVisible(true);
    }//GEN-LAST:event_menuSearchCustomerActionPerformed

    private void menuAddFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddFlightActionPerformed
        // TODO add your handling code here:
        AddFlight af = new AddFlight();
        jDesktopPane1.add(af);
        af.setVisible(true);
    }//GEN-LAST:event_menuAddFlightActionPerformed

    private void menuBookTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBookTicketActionPerformed
        // TODO add your handling code here:
        Ticket t = new Ticket();
        jDesktopPane1.add(t);
        t.setVisible(true);
    }//GEN-LAST:event_menuBookTicketActionPerformed

    private void menuSearchFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSearchFlightActionPerformed
        // TODO add your handling code here:
        SearchFlight sf = new SearchFlight();
        jDesktopPane1.add(sf);
        sf.setVisible(true);
    }//GEN-LAST:event_menuSearchFlightActionPerformed

    private void menuTicketReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTicketReportActionPerformed
        // TODO add your handling code here:
        TicketReport tr = new TicketReport();
        jDesktopPane1.add(tr);
        tr.setVisible(true);
    }//GEN-LAST:event_menuTicketReportActionPerformed

    private void menuCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCreateUserActionPerformed
        // TODO add your handling code here:
        UserCreation uc = new UserCreation();
        jDesktopPane1.add(uc);
        uc.setVisible(true);
    }//GEN-LAST:event_menuCreateUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAddCustomer;
    private javax.swing.JMenuItem menuAddFlight;
    private javax.swing.JMenuItem menuBookTicket;
    private javax.swing.JMenuItem menuCreateUser;
    private javax.swing.JMenu menuCustomer;
    private javax.swing.JMenuItem menuSearchCustomer;
    private javax.swing.JMenuItem menuSearchFlight;
    private javax.swing.JMenuItem menuTicketReport;
    // End of variables declaration//GEN-END:variables
}
